name: Desplegar GitHub Pages

on:
  push:
    branches:
      - master # o main, dependiendo de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # o la versión que estés usando

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install # o npm install, si estás usando npm

      - name: Construir el proyecto
        run: pnpm run build # o npm run build

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # La carpeta con los archivos construidos
          token: ${{ secrets.ACCESS_TOKEN }} # Usa el secreto
